remove member caching
KittyBot-Org/KittyBot pull request #117
Opened 2020-09-30 15:14 UTC by caneleex

2020-10-01 12:38 UTC, caneleex commented
@TopiSenpai is there a way for us to test session(cache) changes?

2020-10-01 23:24 UTC, TopiSenpai requested changes
lgtm except as said un/caching on perm update is missing

2020-10-01 23:33 UTC, TopiSenpai commented
todo: before merging remove session table so it get's newly generated

2020-10-02 23:36 UTC, TopiSenpai approved these changes

2020-10-02 23:38 UTC, TopiSenpai approved these changes

2020-10-02 23:39 UTC, merged